Declare @SQL Varchar(200)

------ECM72-----
Select @SQL = 'ALTER DATABASE ECM72 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;';exec (@SQL);
RESTORE DATABASE "ECM72" FROM DISK = 'C:\DOXIMECM72\DB_Backup_Restore\DoximAutoTest72_201305.bak' With Replace ;
Select @SQL = 'ALTER DATABASE ECM72 SET MULTI_USER WITH ROLLBACK IMMEDIATE;';exec (@SQL);

------ECM72H-----
Select @SQL = 'ALTER DATABASE ECM72H SET SINGLE_USER WITH ROLLBACK IMMEDIATE;';exec (@SQL);
RESTORE DATABASE "ECM72H" FROM DISK = 'C:\DOXIMECM72Home\DB_Backup_Restore\DoximAutoTestH72_201305.bak' With Replace ;
Select @SQL = 'ALTER DATABASE ECM72H SET MULTI_USER WITH ROLLBACK IMMEDIATE;';exec (@SQL);

------ECM72-----
--Select @SQL = 'ALTER DATABASE ECM72 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;';exec (@SQL);
--RESTORE DATABASE "ECM72" FROM DISK = 'C:\*.BAK' WITH MOVE 'ECM72_dat' TO 'C:\*.MDF', MOVE 'ECM72_log' TO 'C:\*.LDF';
--Select @SQL = 'ALTER DATABASE ECM72 SET MULTI_USER WITH ROLLBACK IMMEDIATE;';exec (@SQL);

------ECM72H-----
--Select @SQL = 'ALTER DATABASE ECM72H SET SINGLE_USER WITH ROLLBACK IMMEDIATE;';exec (@SQL);
--RESTORE DATABASE "ECM72H" FROM DISK = 'C:\*.BAK' WITH MOVE 'ECM72H_dat' TO 'C:\*.MDF', MOVE 'ECM72H_log' TO 'C:\*.LDF';
--Select @SQL = 'ALTER DATABASE ECM72H SET MULTI_USER WITH ROLLBACK IMMEDIATE;';exec (@SQL);
